// Mocks generated by Mockito 5.4.6 from annotations
// in autobid_mobile/test/modules/browse/presentation/pages/browse_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:autobid_mobile/modules/browse/domain/entities/auction_entity.dart'
    as _i4;
import 'package:autobid_mobile/modules/browse/domain/entities/auction_filter.dart'
    as _i2;
import 'package:autobid_mobile/modules/browse/presentation/controllers/browse_controller.dart'
    as _i3;
import 'package:autobid_mobile/modules/notifications/domain/entities/notification_entity.dart'
    as _i8;
import 'package:autobid_mobile/modules/notifications/presentation/controllers/notification_controller.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuctionFilter_0 extends _i1.SmartFake implements _i2.AuctionFilter {
  _FakeAuctionFilter_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BrowseController].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrowseController extends _i1.Mock implements _i3.BrowseController {
  MockBrowseController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.AuctionEntity> get auctions =>
      (super.noSuchMethod(
            Invocation.getter(#auctions),
            returnValue: <_i4.AuctionEntity>[],
          )
          as List<_i4.AuctionEntity>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  _i2.AuctionFilter get currentFilter =>
      (super.noSuchMethod(
            Invocation.getter(#currentFilter),
            returnValue: _FakeAuctionFilter_0(
              this,
              Invocation.getter(#currentFilter),
            ),
          )
          as _i2.AuctionFilter);

  @override
  bool get hasActiveFilters =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveFilters),
            returnValue: false,
          )
          as bool);

  @override
  int get activeFilterCount =>
      (super.noSuchMethod(Invocation.getter(#activeFilterCount), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadAuctions({bool? isBackground = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadAuctions, [], {#isBackground: isBackground}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> applyFilter(_i2.AuctionFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#applyFilter, [filter]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateFilter({
    String? searchQuery,
    String? make,
    String? model,
    int? yearFrom,
    int? yearTo,
    double? priceMin,
    double? priceMax,
    String? transmission,
    String? fuelType,
    String? driveType,
    String? condition,
    int? maxMileage,
    String? exteriorColor,
    String? province,
    String? city,
    bool? endingSoon,
    String? visibility,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFilter, [], {
              #searchQuery: searchQuery,
              #make: make,
              #model: model,
              #yearFrom: yearFrom,
              #yearTo: yearTo,
              #priceMin: priceMin,
              #priceMax: priceMax,
              #transmission: transmission,
              #fuelType: fuelType,
              #driveType: driveType,
              #condition: condition,
              #maxMileage: maxMileage,
              #exteriorColor: exteriorColor,
              #province: province,
              #city: city,
              #endingSoon: endingSoon,
              #visibility: visibility,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearFilters() =>
      (super.noSuchMethod(
            Invocation.method(#clearFilters, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateSearchQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#updateSearchQuery, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchAuctions(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchAuctions, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationController extends _i1.Mock
    implements _i7.NotificationController {
  MockNotificationController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.NotificationEntity> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: <_i8.NotificationEntity>[],
          )
          as List<_i8.NotificationEntity>);

  @override
  int get unreadCount =>
      (super.noSuchMethod(Invocation.getter(#unreadCount), returnValue: 0)
          as int);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> loadNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadNotifications, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAsRead(String? notificationId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAllAsRead(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteNotification(String? notificationId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> respondToInvite(
    String? inviteId,
    String? decision,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#respondToInvite, [inviteId, decision, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
