// Mocks generated by Mockito 5.4.6 from annotations
// in autobid_mobile/test/features_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:autobid_mobile/core/error/failures.dart' as _i7;
import 'package:autobid_mobile/modules/auth/domain/entities/kyc_registration_entity.dart'
    as _i12;
import 'package:autobid_mobile/modules/auth/domain/entities/user_entity.dart'
    as _i11;
import 'package:autobid_mobile/modules/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:autobid_mobile/modules/auth/domain/usecases/send_email_otp_usecase.dart'
    as _i16;
import 'package:autobid_mobile/modules/lists/domain/entities/seller_listing_entity.dart'
    as _i8;
import 'package:autobid_mobile/modules/lists/domain/repositories/seller_repository.dart'
    as _i2;
import 'package:autobid_mobile/modules/lists/domain/usecases/delete_listing_usecase.dart'
    as _i14;
import 'package:autobid_mobile/modules/lists/domain/usecases/get_seller_listings_usecase.dart'
    as _i4;
import 'package:autobid_mobile/modules/lists/domain/usecases/stream_seller_listings_usecase.dart'
    as _i10;
import 'package:autobid_mobile/modules/lists/domain/usecases/submission_usecases.dart'
    as _i13;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSellerRepository_0 extends _i1.SmartFake
    implements _i2.SellerRepository {
  _FakeSellerRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_1 extends _i1.SmartFake
    implements _i3.AuthRepository {
  _FakeAuthRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSellerListingsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSellerListingsUseCase extends _i1.Mock
    implements _i4.GetSellerListingsUseCase {
  MockGetSellerListingsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<
    _i6.Either<
      _i7.Failure,
      Map<_i8.ListingStatus, List<_i8.SellerListingEntity>>
    >
  >
  call(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [sellerId]),
            returnValue:
                _i5.Future<
                  _i6.Either<
                    _i7.Failure,
                    Map<_i8.ListingStatus, List<_i8.SellerListingEntity>>
                  >
                >.value(
                  _i9.dummyValue<
                    _i6.Either<
                      _i7.Failure,
                      Map<_i8.ListingStatus, List<_i8.SellerListingEntity>>
                    >
                  >(this, Invocation.method(#call, [sellerId])),
                ),
          )
          as _i5.Future<
            _i6.Either<
              _i7.Failure,
              Map<_i8.ListingStatus, List<_i8.SellerListingEntity>>
            >
          >);
}

/// A class which mocks [StreamSellerListingsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamSellerListingsUseCase extends _i1.Mock
    implements _i10.StreamSellerListingsUseCase {
  MockStreamSellerListingsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Stream<void> call(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [sellerId]),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity?>>.value(
                  _i9.dummyValue<_i6.Either<_i7.Failure, _i11.UserEntity?>>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity?>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>> signInWithUsername(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithUsername, [username, password]),
            returnValue:
                _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>>.value(
                  _i9.dummyValue<_i6.Either<_i7.Failure, _i11.UserEntity>>(
                    this,
                    Invocation.method(#signInWithUsername, [
                      username,
                      password,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>>.value(
                  _i9.dummyValue<_i6.Either<_i7.Failure, _i11.UserEntity>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> sendPasswordResetRequest(
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetRequest, [username]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#sendPasswordResetRequest, [username]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> verifyOtp(
    String? username,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [username, otp]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#verifyOtp, [username, otp]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> resetPassword(
    String? username,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [username, newPassword]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#resetPassword, [username, newPassword]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>> signUp(
    String? email,
    String? password, {
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #signUp,
              [email, password],
              {#username: username},
            ),
            returnValue:
                _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>>.value(
                  _i9.dummyValue<_i6.Either<_i7.Failure, _i11.UserEntity>>(
                    this,
                    Invocation.method(
                      #signUp,
                      [email, password],
                      {#username: username},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i11.UserEntity>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> sendEmailOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailOtp, [email]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#sendEmailOtp, [email]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> sendPhoneOtp(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#sendPhoneOtp, [phoneNumber]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#sendPhoneOtp, [phoneNumber]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> verifyEmailOtp(
    String? email,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailOtp, [email, otp]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#verifyEmailOtp, [email, otp]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> verifyPhoneOtp(
    String? phoneNumber,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneOtp, [phoneNumber, otp]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#verifyPhoneOtp, [phoneNumber, otp]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> submitKycRegistration(
    _i12.KycRegistrationEntity? kycData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitKycRegistration, [kycData]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#submitKycRegistration, [kycData]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i12.KycRegistrationEntity?>>
  getKycRegistrationStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getKycRegistrationStatus, [userId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, _i12.KycRegistrationEntity?>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, _i12.KycRegistrationEntity?>
                  >(
                    this,
                    Invocation.method(#getKycRegistrationStatus, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i12.KycRegistrationEntity?>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> checkUsernameAvailable(
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkUsernameAvailable, [username]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#checkUsernameAvailable, [username]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> checkEmailAvailable(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailAvailable, [email]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#checkEmailAvailable, [email]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> checkNationalIdExists(
    String? idNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkNationalIdExists, [idNumber]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#checkNationalIdExists, [idNumber]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> checkSecondaryIdExists(
    String? idNumber,
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkSecondaryIdExists, [idNumber, type]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#checkSecondaryIdExists, [idNumber, type]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> cacheRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#cacheRememberMe, [value]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#cacheRememberMe, [value]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> getRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#getRememberMe, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#getRememberMe, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> cacheUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUsername, [username]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#cacheUsername, [username]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, String?>> getCachedUsername() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUsername, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, String?>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, String?>>(
                this,
                Invocation.method(#getCachedUsername, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, String?>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> clearCachedUsername() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedUsername, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#clearCachedUsername, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> cacheOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#cacheOnboardingCompleted, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#cacheOnboardingCompleted, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, bool>> getOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingCompleted, []),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, bool>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, bool>>(
                this,
                Invocation.method(#getOnboardingCompleted, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, bool>>);
}

/// A class which mocks [DeleteDraftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteDraftUseCase extends _i1.Mock
    implements _i13.DeleteDraftUseCase {
  MockDeleteDraftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [draftId]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [draftId]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [DeleteListingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteListingUseCase extends _i1.Mock
    implements _i14.DeleteListingUseCase {
  MockDeleteListingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? auctionId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [auctionId]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [auctionId]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [CancelListingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelListingUseCase extends _i1.Mock
    implements _i13.CancelListingUseCase {
  MockCancelListingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? auctionId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [auctionId]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [auctionId]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i15.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i5.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SendEmailOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendEmailOtpUseCase extends _i1.Mock
    implements _i16.SendEmailOtpUseCase {
  MockSendEmailOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.AuthRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [email]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}
