// Mocks generated by Mockito 5.4.6 from annotations
// in autobid_mobile/test/modules/lists/presentation/widgets/listing_form/step8_final_details_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:autobid_mobile/modules/lists/domain/entities/listing_draft_entity.dart'
    as _i3;
import 'package:autobid_mobile/modules/lists/domain/entities/vehicle_entities.dart'
    as _i4;
import 'package:autobid_mobile/modules/lists/presentation/controllers/listing_draft_controller.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ListingDraftController].
///
/// See the documentation for Mockito's code generation for more information.
class MockListingDraftController extends _i1.Mock
    implements _i2.ListingDraftController {
  MockListingDraftController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ListingDraftEntity> get drafts =>
      (super.noSuchMethod(
            Invocation.getter(#drafts),
            returnValue: <_i3.ListingDraftEntity>[],
          )
          as List<_i3.ListingDraftEntity>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isSaving =>
      (super.noSuchMethod(Invocation.getter(#isSaving), returnValue: false)
          as bool);

  @override
  bool get isSubmitting =>
      (super.noSuchMethod(Invocation.getter(#isSubmitting), returnValue: false)
          as bool);

  @override
  bool get isSubmissionSuccess =>
      (super.noSuchMethod(
            Invocation.getter(#isSubmissionSuccess),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  List<_i4.VehicleBrand> get brands =>
      (super.noSuchMethod(
            Invocation.getter(#brands),
            returnValue: <_i4.VehicleBrand>[],
          )
          as List<_i4.VehicleBrand>);

  @override
  List<_i4.VehicleModel> get models =>
      (super.noSuchMethod(
            Invocation.getter(#models),
            returnValue: <_i4.VehicleModel>[],
          )
          as List<_i4.VehicleModel>);

  @override
  List<_i4.VehicleVariant> get variants =>
      (super.noSuchMethod(
            Invocation.getter(#variants),
            returnValue: <_i4.VehicleVariant>[],
          )
          as List<_i4.VehicleVariant>);

  @override
  bool get isLoadingVehicleData =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingVehicleData),
            returnValue: false,
          )
          as bool);

  @override
  int get currentStep =>
      (super.noSuchMethod(Invocation.getter(#currentStep), returnValue: 0)
          as int);

  @override
  bool get canGoNext =>
      (super.noSuchMethod(Invocation.getter(#canGoNext), returnValue: false)
          as bool);

  @override
  bool get canGoPrevious =>
      (super.noSuchMethod(Invocation.getter(#canGoPrevious), returnValue: false)
          as bool);

  @override
  bool get canSubmit =>
      (super.noSuchMethod(Invocation.getter(#canSubmit), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> loadBrands() =>
      (super.noSuchMethod(
            Invocation.method(#loadBrands, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadModels(String? brandName) =>
      (super.noSuchMethod(
            Invocation.method(#loadModels, [brandName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadVariants(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#loadVariants, [modelName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadDrafts(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#loadDrafts, [sellerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadDraft(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#loadDraft, [draftId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createNewDraft(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#createNewDraft, [sellerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void updateDraft(_i3.ListingDraftEntity? updatedDraft) => super.noSuchMethod(
    Invocation.method(#updateDraft, [updatedDraft]),
    returnValueForMissingStub: null,
  );

  @override
  void goToNextStep() => super.noSuchMethod(
    Invocation.method(#goToNextStep, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToPreviousStep() => super.noSuchMethod(
    Invocation.method(#goToPreviousStep, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToStep(int? step) => super.noSuchMethod(
    Invocation.method(#goToStep, [step]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> saveDraft() =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> uploadPhoto(
    String? categoryDisplayName,
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [categoryDisplayName, localPath]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> uploadDeedOfSale(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDeedOfSale, [localPath]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> removeDeedOfSale() =>
      (super.noSuchMethod(
            Invocation.method(#removeDeedOfSale, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> submitListing(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#submitListing, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteDraft(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, [draftId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
