// Mocks generated by Mockito 5.4.6 from annotations
// in autobid_mobile/test/modules/transactions/installment_tracker_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i9;

import 'package:autobid_mobile/modules/transactions/data/datasources/installment_supabase_datasource.dart'
    as _i3;
import 'package:autobid_mobile/modules/transactions/data/datasources/transaction_realtime_datasource.dart'
    as _i7;
import 'package:autobid_mobile/modules/transactions/domain/entities/agreement_field_entity.dart'
    as _i11;
import 'package:autobid_mobile/modules/transactions/domain/entities/installment_payment_entity.dart'
    as _i5;
import 'package:autobid_mobile/modules/transactions/domain/entities/installment_plan_entity.dart'
    as _i2;
import 'package:autobid_mobile/modules/transactions/domain/entities/payment_attempt_entity.dart'
    as _i6;
import 'package:autobid_mobile/modules/transactions/domain/entities/transaction_entity.dart'
    as _i8;
import 'package:autobid_mobile/modules/transactions/domain/entities/transaction_review_entity.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInstallmentPlanEntity_0 extends _i1.SmartFake
    implements _i2.InstallmentPlanEntity {
  _FakeInstallmentPlanEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InstallmentSupabaseDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstallmentSupabaseDatasource extends _i1.Mock
    implements _i3.InstallmentSupabaseDatasource {
  MockInstallmentSupabaseDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InstallmentPlanEntity?> getInstallmentPlan(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInstallmentPlan, [transactionId]),
            returnValue: _i4.Future<_i2.InstallmentPlanEntity?>.value(),
          )
          as _i4.Future<_i2.InstallmentPlanEntity?>);

  @override
  _i4.Future<_i2.InstallmentPlanEntity> createInstallmentPlan({
    required String? transactionId,
    required double? totalAmount,
    required double? downPayment,
    required int? numInstallments,
    required String? frequency,
    required DateTime? startDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInstallmentPlan, [], {
              #transactionId: transactionId,
              #totalAmount: totalAmount,
              #downPayment: downPayment,
              #numInstallments: numInstallments,
              #frequency: frequency,
              #startDate: startDate,
            }),
            returnValue: _i4.Future<_i2.InstallmentPlanEntity>.value(
              _FakeInstallmentPlanEntity_0(
                this,
                Invocation.method(#createInstallmentPlan, [], {
                  #transactionId: transactionId,
                  #totalAmount: totalAmount,
                  #downPayment: downPayment,
                  #numInstallments: numInstallments,
                  #frequency: frequency,
                  #startDate: startDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.InstallmentPlanEntity>);

  @override
  _i4.Future<_i2.InstallmentPlanEntity> updateInstallmentPlan({
    required String? planId,
    required String? transactionId,
    required double? totalAmount,
    required double? downPayment,
    required int? numInstallments,
    required String? frequency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateInstallmentPlan, [], {
              #planId: planId,
              #transactionId: transactionId,
              #totalAmount: totalAmount,
              #downPayment: downPayment,
              #numInstallments: numInstallments,
              #frequency: frequency,
            }),
            returnValue: _i4.Future<_i2.InstallmentPlanEntity>.value(
              _FakeInstallmentPlanEntity_0(
                this,
                Invocation.method(#updateInstallmentPlan, [], {
                  #planId: planId,
                  #transactionId: transactionId,
                  #totalAmount: totalAmount,
                  #downPayment: downPayment,
                  #numInstallments: numInstallments,
                  #frequency: frequency,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.InstallmentPlanEntity>);

  @override
  _i4.Future<List<_i5.InstallmentPaymentEntity>> generatePaymentSchedule({
    required String? planId,
    required double? downPayment,
    required double? remaining,
    required int? numInstallments,
    required String? frequency,
    required DateTime? startDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePaymentSchedule, [], {
              #planId: planId,
              #downPayment: downPayment,
              #remaining: remaining,
              #numInstallments: numInstallments,
              #frequency: frequency,
              #startDate: startDate,
            }),
            returnValue: _i4.Future<List<_i5.InstallmentPaymentEntity>>.value(
              <_i5.InstallmentPaymentEntity>[],
            ),
          )
          as _i4.Future<List<_i5.InstallmentPaymentEntity>>);

  @override
  _i4.Future<List<_i5.InstallmentPaymentEntity>> getPayments(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayments, [planId]),
            returnValue: _i4.Future<List<_i5.InstallmentPaymentEntity>>.value(
              <_i5.InstallmentPaymentEntity>[],
            ),
          )
          as _i4.Future<List<_i5.InstallmentPaymentEntity>>);

  @override
  _i4.Future<void> submitPayment({
    required String? paymentId,
    required double? amount,
    required String? proofImagePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitPayment, [], {
              #paymentId: paymentId,
              #amount: amount,
              #proofImagePath: proofImagePath,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmPayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPayment, [paymentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rejectPayment(String? paymentId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#rejectPayment, [paymentId, reason]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.PaymentAttemptEntity>> getPaymentAttempts(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentAttempts, [paymentId]),
            returnValue: _i4.Future<List<_i6.PaymentAttemptEntity>>.value(
              <_i6.PaymentAttemptEntity>[],
            ),
          )
          as _i4.Future<List<_i6.PaymentAttemptEntity>>);

  @override
  _i4.Stream<_i2.InstallmentPlanEntity?> streamInstallmentPlan(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamInstallmentPlan, [transactionId]),
            returnValue: _i4.Stream<_i2.InstallmentPlanEntity?>.empty(),
          )
          as _i4.Stream<_i2.InstallmentPlanEntity?>);

  @override
  _i4.Stream<List<_i5.InstallmentPaymentEntity>> streamPayments(
    String? planId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamPayments, [planId]),
            returnValue: _i4.Stream<List<_i5.InstallmentPaymentEntity>>.empty(),
          )
          as _i4.Stream<List<_i5.InstallmentPaymentEntity>>);
}

/// A class which mocks [TransactionRealtimeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRealtimeDataSource extends _i1.Mock
    implements _i7.TransactionRealtimeDataSource {
  MockTransactionRealtimeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.ChatMessageEntity> get chatStream =>
      (super.noSuchMethod(
            Invocation.getter(#chatStream),
            returnValue: _i4.Stream<_i8.ChatMessageEntity>.empty(),
          )
          as _i4.Stream<_i8.ChatMessageEntity>);

  @override
  _i4.Stream<Map<String, dynamic>> get transactionUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#transactionUpdateStream),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<void> get userTransactionsUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#userTransactionsUpdateStream),
            returnValue: _i4.Stream<void>.empty(),
          )
          as _i4.Stream<void>);

  @override
  void subscribeToUserTransactions(String? userId) => super.noSuchMethod(
    Invocation.method(#subscribeToUserTransactions, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i8.TransactionEntity?> getTransactionByAuctionId(
    String? auctionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionByAuctionId, [auctionId]),
            returnValue: _i4.Future<_i8.TransactionEntity?>.value(),
          )
          as _i4.Future<_i8.TransactionEntity?>);

  @override
  _i4.Future<_i8.TransactionEntity?> getTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [transactionId]),
            returnValue: _i4.Future<_i8.TransactionEntity?>.value(),
          )
          as _i4.Future<_i8.TransactionEntity?>);

  @override
  _i4.Future<List<_i8.ChatMessageEntity>> getChatMessages(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [transactionId]),
            returnValue: _i4.Future<List<_i8.ChatMessageEntity>>.value(
              <_i8.ChatMessageEntity>[],
            ),
          )
          as _i4.Future<List<_i8.ChatMessageEntity>>);

  @override
  _i4.Future<_i8.ChatMessageEntity?> sendMessage(
    String? transactionId,
    String? senderId,
    String? senderName,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              transactionId,
              senderId,
              senderName,
              message,
            ]),
            returnValue: _i4.Future<_i8.ChatMessageEntity?>.value(),
          )
          as _i4.Future<_i8.ChatMessageEntity?>);

  @override
  void subscribeToChat(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToChat, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i8.TransactionFormEntity?> getTransactionForm(
    String? transactionId,
    _i8.FormRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionForm, [transactionId, role]),
            returnValue: _i4.Future<_i8.TransactionFormEntity?>.value(),
          )
          as _i4.Future<_i8.TransactionFormEntity?>);

  @override
  _i4.Future<_i8.TransactionFormEntity?> submitForm(
    _i8.TransactionFormEntity? form,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitForm, [form]),
            returnValue: _i4.Future<_i8.TransactionFormEntity?>.value(),
          )
          as _i4.Future<_i8.TransactionFormEntity?>);

  @override
  _i4.Future<bool> confirmForm(
    String? transactionId,
    _i8.FormRole? roleToConfirm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmForm, [transactionId, roleToConfirm]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> withdrawConfirmation(
    String? transactionId,
    _i8.FormRole? roleToWithdraw,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withdrawConfirmation, [
              transactionId,
              roleToWithdraw,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> cancelDeal(
    String? transactionId,
    _i8.FormRole? role, {
    String? reason = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cancelDeal,
              [transactionId, role],
              {#reason: reason},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> offerToNextHighestBidder(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#offerToNextHighestBidder, [transactionId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> relistAuction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#relistAuction, [transactionId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteAuction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAuction, [transactionId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAuctionBidders(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAuctionBidders, [transactionId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> offerToSpecificBidder(
    String? transactionId,
    String? newBidderId,
    double? bidAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#offerToSpecificBidder, [
              transactionId,
              newBidderId,
              bidAmount,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateDeliveryStatus(
    String? transactionId,
    String? sellerId,
    _i8.DeliveryStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeliveryStatus, [
              transactionId,
              sellerId,
              status,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> respondToDelivery({
    required String? transactionId,
    required String? buyerId,
    required bool? accepted,
    String? rejectionReason,
    List<_i9.File>? rejectionPhotos,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#respondToDelivery, [], {
              #transactionId: transactionId,
              #buyerId: buyerId,
              #accepted: accepted,
              #rejectionReason: rejectionReason,
              #rejectionPhotos: rejectionPhotos,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> uploadChecklistPhoto(
    String? transactionId,
    _i9.File? photo,
    String? stepKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadChecklistPhoto, [
              transactionId,
              photo,
              stepKey,
            ]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> updateDeliveryStatusWithPhoto(
    String? transactionId,
    String? sellerId,
    _i8.DeliveryStatus? status,
    _i9.File? photo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeliveryStatusWithPhoto, [
              transactionId,
              sellerId,
              status,
              photo,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> uploadBuyerDeliveryPhoto(
    String? transactionId,
    _i9.File? photo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBuyerDeliveryPhoto, [
              transactionId,
              photo,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i10.TransactionReviewEntity?> submitReview({
    required String? transactionId,
    required String? reviewerId,
    required String? revieweeId,
    required int? rating,
    int? ratingCommunication,
    int? ratingReliability,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitReview, [], {
              #transactionId: transactionId,
              #reviewerId: reviewerId,
              #revieweeId: revieweeId,
              #rating: rating,
              #ratingCommunication: ratingCommunication,
              #ratingReliability: ratingReliability,
              #comment: comment,
            }),
            returnValue: _i4.Future<_i10.TransactionReviewEntity?>.value(),
          )
          as _i4.Future<_i10.TransactionReviewEntity?>);

  @override
  _i4.Future<_i10.TransactionReviewEntity?> getReview(
    String? transactionId,
    String? reviewerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReview, [transactionId, reviewerId]),
            returnValue: _i4.Future<_i10.TransactionReviewEntity?>.value(),
          )
          as _i4.Future<_i10.TransactionReviewEntity?>);

  @override
  _i4.Future<List<_i8.TransactionTimelineEntity>> getTimeline(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeline, [transactionId]),
            returnValue: _i4.Future<List<_i8.TransactionTimelineEntity>>.value(
              <_i8.TransactionTimelineEntity>[],
            ),
          )
          as _i4.Future<List<_i8.TransactionTimelineEntity>>);

  @override
  void subscribeToTransaction(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToTransaction, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  void subscribeToForms(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToForms, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  void subscribeToTimeline(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToTimeline, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i11.AgreementFieldEntity>> getAgreementFields(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAgreementFields, [transactionId]),
            returnValue: _i4.Future<List<_i11.AgreementFieldEntity>>.value(
              <_i11.AgreementFieldEntity>[],
            ),
          )
          as _i4.Future<List<_i11.AgreementFieldEntity>>);

  @override
  _i4.Future<_i11.AgreementFieldEntity?> addAgreementField({
    required String? transactionId,
    required String? label,
    String? value = '',
    String? fieldType = 'text',
    String? category = 'general',
    String? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAgreementField, [], {
              #transactionId: transactionId,
              #label: label,
              #value: value,
              #fieldType: fieldType,
              #category: category,
              #options: options,
            }),
            returnValue: _i4.Future<_i11.AgreementFieldEntity?>.value(),
          )
          as _i4.Future<_i11.AgreementFieldEntity?>);

  @override
  _i4.Future<bool> updateAgreementField(
    String? fieldId,
    String? value, {
    String? editedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateAgreementField,
              [fieldId, value],
              {#editedBy: editedBy},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteAgreementField(String? fieldId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAgreementField, [fieldId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> lockAgreement(String? transactionId, _i8.FormRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#lockAgreement, [transactionId, role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> unlockAgreement(String? transactionId, _i8.FormRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#unlockAgreement, [transactionId, role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> confirmAgreement(
    String? transactionId,
    _i8.FormRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmAgreement, [transactionId, role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> withdrawAgreementConfirmation(
    String? transactionId,
    _i8.FormRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withdrawAgreementConfirmation, [
              transactionId,
              role,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> finalizeTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeTransaction, [transactionId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void subscribeToAgreementFields(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToAgreementFields, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribeDetailChannels() => super.noSuchMethod(
    Invocation.method(#unsubscribeDetailChannels, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> updatePaymentMethod(String? transactionId, String? method) =>
      (super.noSuchMethod(
            Invocation.method(#updatePaymentMethod, [transactionId, method]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
