// Mocks generated by Mockito 5.4.6 from annotations
// in autobid_mobile/test/modules/lists/presentation/controllers/listing_draft_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i12;

import 'package:autobid_mobile/core/error/failures.dart' as _i7;
import 'package:autobid_mobile/modules/lists/domain/entities/listing_draft_entity.dart'
    as _i8;
import 'package:autobid_mobile/modules/lists/domain/entities/vehicle_entities.dart'
    as _i14;
import 'package:autobid_mobile/modules/lists/domain/repositories/seller_repository.dart'
    as _i2;
import 'package:autobid_mobile/modules/lists/domain/repositories/vehicle_repository.dart'
    as _i3;
import 'package:autobid_mobile/modules/lists/domain/usecases/draft_management_usecases.dart'
    as _i4;
import 'package:autobid_mobile/modules/lists/domain/usecases/get_vehicle_data_usecases.dart'
    as _i13;
import 'package:autobid_mobile/modules/lists/domain/usecases/media_management_usecases.dart'
    as _i11;
import 'package:autobid_mobile/modules/lists/domain/usecases/submission_usecases.dart'
    as _i10;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSellerRepository_0 extends _i1.SmartFake
    implements _i2.SellerRepository {
  _FakeSellerRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVehicleRepository_1 extends _i1.SmartFake
    implements _i3.VehicleRepository {
  _FakeVehicleRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSellerDraftsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSellerDraftsUseCase extends _i1.Mock
    implements _i4.GetSellerDraftsUseCase {
  MockGetSellerDraftsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, List<_i8.ListingDraftEntity>>> call(
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [sellerId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, List<_i8.ListingDraftEntity>>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, List<_i8.ListingDraftEntity>>
                  >(this, Invocation.method(#call, [sellerId])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, List<_i8.ListingDraftEntity>>>);
}

/// A class which mocks [GetDraftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDraftUseCase extends _i1.Mock implements _i4.GetDraftUseCase {
  MockGetDraftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i8.ListingDraftEntity?>> call(
    String? draftId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [draftId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, _i8.ListingDraftEntity?>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, _i8.ListingDraftEntity?>
                  >(this, Invocation.method(#call, [draftId])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i8.ListingDraftEntity?>>);
}

/// A class which mocks [CreateDraftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateDraftUseCase extends _i1.Mock
    implements _i4.CreateDraftUseCase {
  MockCreateDraftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i8.ListingDraftEntity>> call(
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [sellerId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, _i8.ListingDraftEntity>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, _i8.ListingDraftEntity>
                  >(this, Invocation.method(#call, [sellerId])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, _i8.ListingDraftEntity>>);
}

/// A class which mocks [SaveDraftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveDraftUseCase extends _i1.Mock implements _i10.SaveDraftUseCase {
  MockSaveDraftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(
    _i8.ListingDraftEntity? draft,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [draft]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [draft]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [MarkDraftCompleteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkDraftCompleteUseCase extends _i1.Mock
    implements _i4.MarkDraftCompleteUseCase {
  MockMarkDraftCompleteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [draftId]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [draftId]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [DeleteDraftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteDraftUseCase extends _i1.Mock
    implements _i10.DeleteDraftUseCase {
  MockDeleteDraftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [draftId]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [draftId]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [SubmitListingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitListingUseCase extends _i1.Mock
    implements _i10.SubmitListingUseCase {
  MockSubmitListingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, String>> call(String? draftId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [draftId]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, String>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, String>>(
                this,
                Invocation.method(#call, [draftId]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, String>>);
}

/// A class which mocks [UploadListingPhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadListingPhotoUseCase extends _i1.Mock
    implements _i11.UploadListingPhotoUseCase {
  MockUploadListingPhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, String>> call({
    required String? userId,
    required String? listingId,
    required String? category,
    required _i12.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #userId: userId,
              #listingId: listingId,
              #category: category,
              #imageFile: imageFile,
            }),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, String>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, String>>(
                this,
                Invocation.method(#call, [], {
                  #userId: userId,
                  #listingId: listingId,
                  #category: category,
                  #imageFile: imageFile,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, String>>);
}

/// A class which mocks [UploadDeedOfSaleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadDeedOfSaleUseCase extends _i1.Mock
    implements _i11.UploadDeedOfSaleUseCase {
  MockUploadDeedOfSaleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, String>> call({
    required String? userId,
    required String? listingId,
    required _i12.File? documentFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #userId: userId,
              #listingId: listingId,
              #documentFile: documentFile,
            }),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, String>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, String>>(
                this,
                Invocation.method(#call, [], {
                  #userId: userId,
                  #listingId: listingId,
                  #documentFile: documentFile,
                }),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, String>>);
}

/// A class which mocks [DeleteDeedOfSaleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteDeedOfSaleUseCase extends _i1.Mock
    implements _i11.DeleteDeedOfSaleUseCase {
  MockDeleteDeedOfSaleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SellerRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSellerRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SellerRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, void>> call(String? documentUrl) =>
      (super.noSuchMethod(
            Invocation.method(#call, [documentUrl]),
            returnValue: _i5.Future<_i6.Either<_i7.Failure, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.Failure, void>>(
                this,
                Invocation.method(#call, [documentUrl]),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, void>>);
}

/// A class which mocks [GetVehicleBrandsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVehicleBrandsUseCase extends _i1.Mock
    implements _i13.GetVehicleBrandsUseCase {
  MockGetVehicleBrandsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VehicleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeVehicleRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.VehicleRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, List<_i14.VehicleBrand>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, List<_i14.VehicleBrand>>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, List<_i14.VehicleBrand>>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, List<_i14.VehicleBrand>>>);
}

/// A class which mocks [GetVehicleModelsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVehicleModelsUseCase extends _i1.Mock
    implements _i13.GetVehicleModelsUseCase {
  MockGetVehicleModelsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VehicleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeVehicleRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.VehicleRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, List<_i14.VehicleModel>>> call(
    String? brandId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [brandId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, List<_i14.VehicleModel>>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, List<_i14.VehicleModel>>
                  >(this, Invocation.method(#call, [brandId])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, List<_i14.VehicleModel>>>);
}

/// A class which mocks [GetVehicleVariantsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVehicleVariantsUseCase extends _i1.Mock
    implements _i13.GetVehicleVariantsUseCase {
  MockGetVehicleVariantsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VehicleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeVehicleRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.VehicleRepository);

  @override
  _i5.Future<_i6.Either<_i7.Failure, List<_i14.VehicleVariant>>> call(
    String? modelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [modelId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.Failure, List<_i14.VehicleVariant>>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.Failure, List<_i14.VehicleVariant>>
                  >(this, Invocation.method(#call, [modelId])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.Failure, List<_i14.VehicleVariant>>>);
}
