// Mocks generated by Mockito 5.4.6 from annotations
// in autobid_mobile/test/modules/transactions/presentation/controllers/transaction_realtime_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:autobid_mobile/modules/transactions/data/datasources/transaction_realtime_datasource.dart'
    as _i2;
import 'package:autobid_mobile/modules/transactions/domain/entities/transaction_entity.dart'
    as _i4;
import 'package:autobid_mobile/modules/transactions/domain/entities/transaction_review_entity.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TransactionRealtimeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRealtimeDataSource extends _i1.Mock
    implements _i2.TransactionRealtimeDataSource {
  MockTransactionRealtimeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.ChatMessageEntity> get chatStream =>
      (super.noSuchMethod(
            Invocation.getter(#chatStream),
            returnValue: _i3.Stream<_i4.ChatMessageEntity>.empty(),
          )
          as _i3.Stream<_i4.ChatMessageEntity>);

  @override
  _i3.Stream<Map<String, dynamic>> get transactionUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#transactionUpdateStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<void> get userTransactionsUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#userTransactionsUpdateStream),
            returnValue: _i3.Stream<void>.empty(),
          )
          as _i3.Stream<void>);

  @override
  void subscribeToUserTransactions(String? userId) => super.noSuchMethod(
    Invocation.method(#subscribeToUserTransactions, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.TransactionEntity?> getTransactionByAuctionId(
    String? auctionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionByAuctionId, [auctionId]),
            returnValue: _i3.Future<_i4.TransactionEntity?>.value(),
          )
          as _i3.Future<_i4.TransactionEntity?>);

  @override
  _i3.Future<_i4.TransactionEntity?> getTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [transactionId]),
            returnValue: _i3.Future<_i4.TransactionEntity?>.value(),
          )
          as _i3.Future<_i4.TransactionEntity?>);

  @override
  _i3.Future<List<_i4.ChatMessageEntity>> getChatMessages(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [transactionId]),
            returnValue: _i3.Future<List<_i4.ChatMessageEntity>>.value(
              <_i4.ChatMessageEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ChatMessageEntity>>);

  @override
  _i3.Future<_i4.ChatMessageEntity?> sendMessage(
    String? transactionId,
    String? senderId,
    String? senderName,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              transactionId,
              senderId,
              senderName,
              message,
            ]),
            returnValue: _i3.Future<_i4.ChatMessageEntity?>.value(),
          )
          as _i3.Future<_i4.ChatMessageEntity?>);

  @override
  void subscribeToChat(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToChat, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.TransactionFormEntity?> getTransactionForm(
    String? transactionId,
    _i4.FormRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionForm, [transactionId, role]),
            returnValue: _i3.Future<_i4.TransactionFormEntity?>.value(),
          )
          as _i3.Future<_i4.TransactionFormEntity?>);

  @override
  _i3.Future<_i4.TransactionFormEntity?> submitForm(
    _i4.TransactionFormEntity? form,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitForm, [form]),
            returnValue: _i3.Future<_i4.TransactionFormEntity?>.value(),
          )
          as _i3.Future<_i4.TransactionFormEntity?>);

  @override
  _i3.Future<bool> confirmForm(
    String? transactionId,
    _i4.FormRole? roleToConfirm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmForm, [transactionId, roleToConfirm]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> withdrawConfirmation(
    String? transactionId,
    _i4.FormRole? roleToWithdraw,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withdrawConfirmation, [
              transactionId,
              roleToWithdraw,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> cancelDeal(
    String? transactionId,
    _i4.FormRole? role, {
    String? reason = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cancelDeal,
              [transactionId, role],
              {#reason: reason},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> offerToNextHighestBidder(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#offerToNextHighestBidder, [transactionId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> relistAuction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#relistAuction, [transactionId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAuction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAuction, [transactionId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAuctionBidders(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAuctionBidders, [transactionId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<bool> offerToSpecificBidder(
    String? transactionId,
    String? newBidderId,
    double? bidAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#offerToSpecificBidder, [
              transactionId,
              newBidderId,
              bidAmount,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateDeliveryStatus(
    String? transactionId,
    String? sellerId,
    _i4.DeliveryStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeliveryStatus, [
              transactionId,
              sellerId,
              status,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> respondToDelivery({
    required String? transactionId,
    required String? buyerId,
    required bool? accepted,
    String? rejectionReason,
    List<_i5.File>? rejectionPhotos,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#respondToDelivery, [], {
              #transactionId: transactionId,
              #buyerId: buyerId,
              #accepted: accepted,
              #rejectionReason: rejectionReason,
              #rejectionPhotos: rejectionPhotos,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i6.TransactionReviewEntity?> submitReview({
    required String? transactionId,
    required String? reviewerId,
    required String? revieweeId,
    required int? rating,
    int? ratingCommunication,
    int? ratingReliability,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitReview, [], {
              #transactionId: transactionId,
              #reviewerId: reviewerId,
              #revieweeId: revieweeId,
              #rating: rating,
              #ratingCommunication: ratingCommunication,
              #ratingReliability: ratingReliability,
              #comment: comment,
            }),
            returnValue: _i3.Future<_i6.TransactionReviewEntity?>.value(),
          )
          as _i3.Future<_i6.TransactionReviewEntity?>);

  @override
  _i3.Future<_i6.TransactionReviewEntity?> getReview(
    String? transactionId,
    String? reviewerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReview, [transactionId, reviewerId]),
            returnValue: _i3.Future<_i6.TransactionReviewEntity?>.value(),
          )
          as _i3.Future<_i6.TransactionReviewEntity?>);

  @override
  _i3.Future<List<_i4.TransactionTimelineEntity>> getTimeline(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeline, [transactionId]),
            returnValue: _i3.Future<List<_i4.TransactionTimelineEntity>>.value(
              <_i4.TransactionTimelineEntity>[],
            ),
          )
          as _i3.Future<List<_i4.TransactionTimelineEntity>>);

  @override
  void subscribeToTransaction(String? transactionId) => super.noSuchMethod(
    Invocation.method(#subscribeToTransaction, [transactionId]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
